[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
authors  = [
    {name = "Will Fatherley", email = "wfatherley@proton.me"}
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]
dependencies = ["nbformat"]
description = "Docstring utilities"
license = "MIT"
maintainers = [
    {name = "Will Fatherley", email = "wfatherley@proton.me"}
]
name = "docrawify"
readme = "README.md"
requires-python = ">=3.9"
version = "2026.0"

[project.scripts]
pydocrawify = "docrawify:main"
